name: uchroma
version: '1.0.2'
summary: Razer Chroma peripheral manager
description: |
 An advanced driver for the Razer Chroma line of peripherals.
 Supports lighting effects, custom animations, and more.

grade: stable
confinement: strict


plugs:
  dbus:
    bus: session
    interface: dbus
    name: org.chemlab.UChroma

slots:
    session-dbus-interface:
      bus: session
      interface: dbus
      name: org.chemlab.UChroma

apps:
  uchroma:
    command: gi-wrap uchroma

  uchromad:
    command: gi-wrap uchromad
    daemon: simple
    plugs:
      - hardware-observe
      - hidraw
      - home
      - raw-usb
      - unity7

parts:
  uchroma:
    source: .
    plugin: python
    python-version: python3
    build-packages:
      - cython3
      - python3-numpy
    stage-packages:
      - python3-gi

  gi-wrap:
    source: snap/
    plugin: dump
    organize:
      gi-wrap: bin/gi-wrap
